### ISSUE TITLE
I can only see 10 instances

### ISSUE THREAD

**Issue by robs-nice99** [hupe1980/gotoaws#6]
When starting a session, without identifying an instance, I get a list of instances. In fact, of only 10. Where are the others?

`gotoaws ec2 session`

**Comment by dstiller** [comment]
You could use search with /. This should be more comfortable with hundreds of servers than scrolling them with the up- and down-keys.

**Comment by dstiller** [comment]
Oh my goodness, you're right. I would not have thought that. I just found the one I was looking for who was in the 10. Then the issue here is entirely justified.

**Comment by dstiller** [comment]
DescribeInstances has a default MaxResults of 10. So hupe1980 needs to implement a loop to get all instances. [Official Documentation on DescribeInstances](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html#API_DescribeInstances_Examples)

**Comment by dstiller** [comment]
Quick fix: Remove the "instanceIDFilter" from Line 62 and 71. Then all instances are listed.
